name: task2
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  equatable: ^2.0.5  

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6